/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.knoldus;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Greetings extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4337628035515539097L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Greetings\",\"namespace\":\"com.knoldus\",\"fields\":[{\"name\":\"greetings\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Greetings> ENCODER =
      new BinaryMessageEncoder<Greetings>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Greetings> DECODER =
      new BinaryMessageDecoder<Greetings>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Greetings> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Greetings> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Greetings> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Greetings>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Greetings to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Greetings from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Greetings instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Greetings fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence greetings;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Greetings() {}

  /**
   * All-args constructor.
   * @param greetings The new value for greetings
   */
  public Greetings(java.lang.CharSequence greetings) {
    this.greetings = greetings;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return greetings;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: greetings = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'greetings' field.
   * @return The value of the 'greetings' field.
   */
  public java.lang.CharSequence getGreetings() {
    return greetings;
  }


  /**
   * Sets the value of the 'greetings' field.
   * @param value the value to set.
   */
  public void setGreetings(java.lang.CharSequence value) {
    this.greetings = value;
  }

  /**
   * Creates a new Greetings RecordBuilder.
   * @return A new Greetings RecordBuilder
   */
  public static com.knoldus.Greetings.Builder newBuilder() {
    return new com.knoldus.Greetings.Builder();
  }

  /**
   * Creates a new Greetings RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Greetings RecordBuilder
   */
  public static com.knoldus.Greetings.Builder newBuilder(com.knoldus.Greetings.Builder other) {
    if (other == null) {
      return new com.knoldus.Greetings.Builder();
    } else {
      return new com.knoldus.Greetings.Builder(other);
    }
  }

  /**
   * Creates a new Greetings RecordBuilder by copying an existing Greetings instance.
   * @param other The existing instance to copy.
   * @return A new Greetings RecordBuilder
   */
  public static com.knoldus.Greetings.Builder newBuilder(com.knoldus.Greetings other) {
    if (other == null) {
      return new com.knoldus.Greetings.Builder();
    } else {
      return new com.knoldus.Greetings.Builder(other);
    }
  }

  /**
   * RecordBuilder for Greetings instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Greetings>
    implements org.apache.avro.data.RecordBuilder<Greetings> {

    private java.lang.CharSequence greetings;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.knoldus.Greetings.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.greetings)) {
        this.greetings = data().deepCopy(fields()[0].schema(), other.greetings);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Greetings instance
     * @param other The existing instance to copy.
     */
    private Builder(com.knoldus.Greetings other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.greetings)) {
        this.greetings = data().deepCopy(fields()[0].schema(), other.greetings);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'greetings' field.
      * @return The value.
      */
    public java.lang.CharSequence getGreetings() {
      return greetings;
    }


    /**
      * Sets the value of the 'greetings' field.
      * @param value The value of 'greetings'.
      * @return This builder.
      */
    public com.knoldus.Greetings.Builder setGreetings(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.greetings = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'greetings' field has been set.
      * @return True if the 'greetings' field has been set, false otherwise.
      */
    public boolean hasGreetings() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'greetings' field.
      * @return This builder.
      */
    public com.knoldus.Greetings.Builder clearGreetings() {
      greetings = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Greetings build() {
      try {
        Greetings record = new Greetings();
        record.greetings = fieldSetFlags()[0] ? this.greetings : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Greetings>
    WRITER$ = (org.apache.avro.io.DatumWriter<Greetings>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Greetings>
    READER$ = (org.apache.avro.io.DatumReader<Greetings>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.greetings);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.greetings = in.readString(this.greetings instanceof Utf8 ? (Utf8)this.greetings : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.greetings = in.readString(this.greetings instanceof Utf8 ? (Utf8)this.greetings : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










